services:
  php:
    build:
      context: ./docker/php
    volumes:
      - .:/var/www/symfony
    working_dir: /var/www/symfony
    environment:
      - DATABASE_URL=mysql://upwork-tracker:12345678@staging-upwork-tracker-mysql:3306/upwork-tracker
      - APP_ENV=dev
      - APP_DEBUG=1
    depends_on:
      - mysql

  nginx:
    image: nginx:latest
    ports:
      - "8081:80"
    volumes:
      - .:/var/www/symfony
      - ./docker/nginx/default.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - php

  mysql:
    image: mysql:8.0
    container_name: staging-upwork-tracker-mysql
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: upwork-tracker
      MYSQL_USER: upwork-tracker
      MYSQL_PASSWORD: 12345678
    ports:
      - "3308:3306"
    volumes:
      - staging_mysql_data:/var/lib/mysql
    command: --default-authentication-plugin=mysql_native_password

volumes:
  staging_mysql_data:
