version: '3.8'

services:
  php:
    build:
      context: ./docker/php
      dockerfile: Dockerfile.prod.fast
      cache_from:
        - php:8.3-fpm
        - composer:latest
    container_name: upwork-tracker-php
    volumes:
      - .:/var/www/symfony
    working_dir: /var/www/symfony
    environment:
      - APP_ENV=${APP_ENV:-prod}
      - APP_DEBUG=${APP_DEBUG:-0}
      - DATABASE_URL=${DATABASE_URL:-mysql://upwork-tracker:${MYSQL_PASSWORD}@mysql:3306/upwork_tracker_prod}
      - UPWORK_API_KEY=${UPWORK_API_KEY}
      - UPWORK_API_SECRET=${UPWORK_API_SECRET}
      - UPWORK_CALLBACK_URL=${UPWORK_CALLBACK_URL}
    depends_on:
      - mysql

  nginx:
    image: nginx:stable-alpine
    container_name: upwork-tracker-nginx
    ports:
      - "8080:80"
    volumes:
      - .:/var/www/symfony
      - ./docker/nginx/default.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - php

  mysql:
    image: mysql:8.0
    container_name: upwork-tracker-mysql
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: upwork_tracker_prod
      MYSQL_USER: upwork-tracker
      MYSQL_PASSWORD: ${MYSQL_PASSWORD:-12345678}
    ports:
      - "3307:3306"
    volumes:
      - mysql_data:/var/lib/mysql
    command: --default-authentication-plugin=mysql_native_password

volumes:
  mysql_data:
