name: Deploy to VPS

on:
  push:
    branches: [ main ]

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Copy files to VPS
        uses: appleboy/scp-action@v0.1.4
        with:
          host: ${{ secrets.VPS_HOST }}
          username: ${{ secrets.VPS_USER }}
          key: ${{ secrets.DIGITAL_OCEAN_VPS_SSH_KEY }}
          source: "."
          target: "/var/www/upwork-tracker.oussema-sferi.dev"

      - name: SSH Build & Restart
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.VPS_HOST }}
          username: ${{ secrets.VPS_USER }}
          key: ${{ secrets.DIGITAL_OCEAN_VPS_SSH_KEY }}
          script: |
            cd /var/www/upwork-tracker.oussema-sferi.dev
            docker compose down
            docker compose up -d --build
            
            # Run composer inside the PHP container
            docker compose exec php composer install --no-dev --optimize-autoloader

            # Clear Symfony cache inside the PHP container
            docker compose exec php php bin/console cache:clear --env=prod