name: Deploy to Production

on:
  push:
    branches: [ main ]

jobs:
  test:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: '8.3'
          extensions: mbstring, xml, ctype, iconv, intl, pdo_mysql, zip, opcache
          coverage: none

      - name: Install dependencies
        run: composer install --prefer-dist --no-progress --no-suggest

      - name: Run tests
        run: php bin/phpunit

  deploy:
    needs: test
    runs-on: ubuntu-latest
    
    steps:
      - name: Deploy to VPS
        uses: appleboy/ssh-action@v0.1.8
        with:
          host: ${{ secrets.VPS_HOST }}
          username: ${{ secrets.VPS_USER }}
          key: ${{ secrets.VPS_SSH_KEY }}
          script: |
            cd /var/www/upwork-tracker-app
            
            # Pull latest code
            git fetch origin main
            git reset --hard origin/main
            
            # Set environment variables from GitHub Secrets
            export APP_ENV=prod
            export APP_DEBUG=0
            export MYSQL_PASSWORD=${{ secrets.MYSQL_PASSWORD_PROD }}
            export DATABASE_URL=mysql://upwork-tracker:${MYSQL_PASSWORD}@mysql:3306/upwork_tracker_prod
            export UPWORK_API_KEY=${{ secrets.UPWORK_API_KEY }}
            export UPWORK_API_SECRET=${{ secrets.UPWORK_API_SECRET }}
            export UPWORK_CALLBACK_URL=https://upwork-tracker.oussema-sferi.dev/oauth/upwork/callback
            
            # Stop existing containers
            docker-compose -f docker-compose.prod.yaml down || true
            
            # Build and start containers
            docker-compose -f docker-compose.prod.yaml up -d --build
            
            # Wait for services to be ready
            sleep 10
            
            # Install dependencies
            docker-compose -f docker-compose.prod.yaml exec -T php composer install --no-dev --optimize-autoloader --no-interaction
            
            # Create database if not exists
            docker-compose -f docker-compose.prod.yaml exec -T php php bin/console doctrine:database:create --if-not-exists --env=prod --no-interaction
            
            # Check if migrations are needed and run them safely
            docker-compose -f docker-compose.prod.yaml exec -T php php bin/console doctrine:migrations:status --no-interaction --env=prod || true
            docker-compose -f docker-compose.prod.yaml exec -T php php bin/console doctrine:migrations:migrate --no-interaction --env=prod || echo "Migrations completed or skipped"
            
            # Clear cache
            docker-compose -f docker-compose.prod.yaml exec -T php php bin/console cache:clear --env=prod --no-interaction
