name: Deploy to Production

on:
  push:
    branches: [ main ]

jobs:
  test:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: '8.3'
          extensions: mbstring, xml, ctype, iconv, intl, pdo_mysql, zip, opcache
          coverage: none

      - name: Install dependencies
        run: composer install --prefer-dist --no-progress --no-suggest

      - name: Run tests
        run: php bin/phpunit

  deploy:
    needs: test
    runs-on: ubuntu-latest
    
    steps:
      - name: Deploy to VPS
        uses: appleboy/ssh-action@v0.1.8
        with:
          host: ${{ secrets.VPS_HOST }}
          username: ${{ secrets.VPS_USER }}
          key: ${{ secrets.VPS_SSH_KEY }}
          script: |
            cd /var/www/upwork-tracker-app
            
            # Pull latest code (faster than SCP)
            git fetch origin main
            git reset --hard origin/main
            
            # Set environment variables
            export MYSQL_PASSWORD=12345678
            
            # Stop existing containers
            docker-compose -f docker-compose.prod.yaml down || true
            
            # Build and start containers (with build cache)
            docker-compose -f docker-compose.prod.yaml up -d --build
            
            # Wait for services to be ready
            sleep 10
            
            # Install dependencies (only if composer.lock changed)
            docker-compose -f docker-compose.prod.yaml exec -T php composer install --no-dev --optimize-autoloader --no-interaction
            
            # Create database if not exists
            docker-compose -f docker-compose.prod.yaml exec -T php php bin/console doctrine:database:create --if-not-exists --env=prod --no-interaction
            
            # Run migrations
            docker-compose -f docker-compose.prod.yaml exec -T php php bin/console doctrine:migrations:migrate --no-interaction --env=prod
            
            # Clear cache
            docker-compose -f docker-compose.prod.yaml exec -T php php bin/console cache:clear --env=prod --no-interaction
